export const bannedChannels = [
    "Sing King",
    "KaraFun Karaoke",
    "Inside Lyric",
    "AKD Entertainment ( Gazal- Qawwali )",
    "Chris Liepe",
    "GoldenKeys Karaoke",
    "Kanta Sonata ",
    "Dhibujo101",
    "LateBloomer",
    "Mga Awit Ni Hiraya",
    "Vicor Music",
    "Lisa and Josh",
    "SILENCEKARAOKE ♫",
    "Justine Calucin",
    "journeyVEVO",
]