export const bannedChannels = [
    "Sing King",
    "KaraFun Karaoke",
    "Inside Lyric",
    "AKD Entertainment ( Gazal- Qawwali )",
    "Chris Liepe",
    "GoldenKeys Karaoke",
    "Kanta Sonata ",
    "Dhibujo101",
    "LateBloomer",
    "Mga Awit Ni Hiraya",
    "Vicor Music",
    "Lisa and Josh",
    "SILENCEKARAOKE ♫",
    "Justine Calucin",
    "journeyVEVO",
    "Lean",
    "Crystal Tone",
    "Jireh Lim",
    "SEDMUSIC",
    "ChoyLyrics",
    "Viva Records",
    "Walk off the Earth",
    "Judy Trisha",
    "Lyrics 90's",
    "SILENCEKARAOKE ♫",
    "GoldenKeys Karaoke",
    "Mik",
    "GIGS",
    "Joyful Lyrics",
    "YerBrigs official ",
    "Dhibujo101",
    "Psalministry Music Channel",
    "MajoysTV",
    "Drojan Project",
    "Moshan official ",
    "WA HERO WORKSHOP 華大俠",
    "CYRELLE BARBO",
    "Vhic Playlist",
    "MYRUS Official",
    "Insight 360 Films",
    "Kayceeology™🎶",
    "Ronnie Liang",
    "Vibe PH",
    "Hawaiian Kine Karaoke",
    "Magnus Haven",
    "Wish 107.5",
    "Nine Degrees North",
    "johnoy danao",
    "Project M Acoustic",
    "Pillow",
    "KaraFun France - Karaoke",
    "Lucy Cover",
    "Luii xiu",
    "Hype Music",
    "senakpop",
    "Brie Brie",
    "Chaeluvvv",
    "Sing India Karaoke",
    "7clouds",
    "PINOkYoPINOYAko",
]