"""add_unique_constraint_to_user

Revision ID: 19a833b87d3e
Revises: 12098693f477
Create Date: 2026-10-01 18:22:00.429587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a833b87d3e'
down_revision: Union[str, Sequence[str], None] = '12098693f477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('provider', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_users_sub_id'), table_name='users')
    op.create_unique_constraint('user_auth_provider_pair', 'users', ['auth_id', 'provider'])
    op.drop_column('users', 'sub_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sub_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('user_auth_provider_pair', 'users', type_='unique')
    op.create_index(op.f('ix_users_sub_id'), 'users', ['sub_id'], unique=True)
    op.drop_column('users', 'provider')
    op.drop_column('users', 'auth_id')
    # ### end Alembic commands ###
