"""add_etag_column

Revision ID: 1c342b421d5c
Revises: a5d0f2a86d85
Create Date: 2026-09-09 15:04:24.586721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c342b421d5c'
down_revision: Union[str, Sequence[str], None] = 'a5d0f2a86d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_cache', sa.Column('etag', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'search_cache', ['etag'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'search_cache', type_='unique')
    op.drop_column('search_cache', 'etag')
    # ### end Alembic commands ###
