"""update title column to text

Revision ID: 843c2e992491
Revises: 9d42b9160742
Create Date: 2026-09-14 23:37:04.979603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '843c2e992491'
down_revision: Union[str, Sequence[str], None] = '9d42b9160742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'title',
               existing_type=sa.VARCHAR(length=99),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=99),
               existing_nullable=False)
    # ### end Alembic commands ###
