"""create_userrole_enum_and_modify_users_table

Revision ID: 89e89b7729b6
Revises: f68853b6e569
Create Date: 2026-10-01 03:13:17.432081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e89b7729b6'
down_revision: Union[str, Sequence[str], None] = 'f68853b6e569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role = sa.Enum('USER', 'ADMIN', name='user_role')
    user_role.create(op.get_bind())

    op.add_column('users', sa.Column('sub_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('picture', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', user_role, nullable=False, server_default="USER"))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_sub_id'), 'users', ['sub_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sub_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')

    op.drop_column('users', 'role')
    op.drop_column('users', 'picture')
    op.drop_column('users', 'name')
    op.drop_column('users', 'sub_id')

    user_role = sa.Enum("USER", "ADMIN", name="user_role")
    user_role.drop(op.get_bind())
    # ### end Alembic commands ###
