"""add_next_videos_table

Revision ID: 9d42b9160742
Revises: 8eed01efc282
Create Date: 2026-09-14 13:58:38.708763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d42b9160742'
down_revision: Union[str, Sequence[str], None] = '8eed01efc282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('next_videos',
    sa.Column('init_video_id', sa.String(length=50), nullable=False),
    sa.Column('next_video_id', sa.String(length=50), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['init_video_id'], ['videos.video_id'], ),
    sa.ForeignKeyConstraint(['next_video_id'], ['videos.video_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('init_video_id', 'next_video_id', name='unq_next_video_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('next_videos')
    # ### end Alembic commands ###
