"""add_cache_tables

Revision ID: a5d0f2a86d85
Revises: e9503a6a3bab
Create Date: 2026-09-08 16:51:08.489076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d0f2a86d85'
down_revision: Union[str, Sequence[str], None] = 'e9503a6a3bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_cache',
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query')
    )
    op.create_table('search_cache_videos',
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['search_cache.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_cache_videos')
    op.drop_table('search_cache')
    # ### end Alembic commands ###
