"""create_ban_request_table

Revision ID: b6b6b9a3652f
Revises: 19a833b87d3e
Create Date: 2026-10-09 15:39:28.832412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b6b9a3652f'
down_revision: Union[str, Sequence[str], None] = '19a833b87d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ban_requests',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('video_id', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='ban_request_status'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.add_column('banned_videos', sa.Column('request_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'banned_videos', 'ban_requests', ['request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'banned_videos', type_='foreignkey')
    op.drop_column('banned_videos', 'request_id')
    op.drop_table('ban_requests')
    # ### end Alembic commands ###
