"""create_banned_videos_table

Revision ID: d9bf6753cf38
Revises: 843c2e992491
Create Date: 2026-09-27 18:16:52.341328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9bf6753cf38'
down_revision: Union[str, Sequence[str], None] = '843c2e992491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned_videos',
    sa.Column('video_id', sa.String(length=50), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_index(op.f('ix_banned_videos_channel_id'), 'banned_videos', ['channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_banned_videos_channel_id'), table_name='banned_videos')
    op.drop_table('banned_videos')
    # ### end Alembic commands ###
