"""add_thumbnail_columns

Revision ID: e9503a6a3bab
Revises: 63704f8675f5
Create Date: 2026-09-08 16:37:38.903874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9503a6a3bab'
down_revision: Union[str, Sequence[str], None] = '63704f8675f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('thumbnail_width', sa.Integer(), nullable=False))
    op.add_column('videos', sa.Column('thumbnail_height', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'thumbnail_height')
    op.drop_column('videos', 'thumbnail_width')
    # ### end Alembic commands ###
