"""add_date_to_banned_videos_table

Revision ID: f68853b6e569
Revises: d9bf6753cf38
Create Date: 2026-09-27 18:56:17.606586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68853b6e569'
down_revision: Union[str, Sequence[str], None] = 'd9bf6753cf38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banned_videos', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banned_videos', 'date')
    # ### end Alembic commands ###
